CREATE DATABASE T_Rental;
GO

USE T_Rental ;
GO

CREATE TABLE EMPRESA(
	cod_empresa SMALLINT PRIMARY KEY IDENTITY (1,1),
	nomeEmpresa VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CLIENTE(
	cod_cliente SMALLINT PRIMARY KEY IDENTITY (1,1),
	nomeCliente VARCHAR(20) NOT NULL,
	sobreNome VARCHAR (50)NOT NULL
);
ALTER TABLE CLIENTE 
ADD dataNascimento date


CREATE TABLE MARCA(
	cod_mar SMALLINT PRIMARY KEY IDENTITY (1,1),
	nomeMar VARCHAR (15) NOT NULL UNIQUE
);

CREATE TABLE MODELO(
	cod_mod SMALLINT PRIMARY KEY IDENTITY (1,1),
	cod_mar SMALLINT FOREIGN KEY REFERENCES MARCA (cod_mar),
	nomemod VARCHAR(15) NOT NULL UNIQUE
);


CREATE TABLE VEICULO(
	cod_veic SMALLINT PRIMARY KEY IDENTITY (1,1),
	cod_empresa SMALLINT FOREIGN KEY REFERENCES EMPRESA (cod_empresa),
	cod_mod SMALLINT FOREIGN KEY REFERENCES MODELO (cod_mod),
	placa CHAR(8) NOT NULL 
);

CREATE TABLE ALUGUEL(
	cod_aluguel SMALLINT PRIMARY KEY IDENTITY (1,1),
	cod_cliente SMALLINT FOREIGN KEY REFERENCES CLIENTE (cod_cliente),
	cod_veic SMALLINT FOREIGN KEY REFERENCES VEICULO (cod_veic),
	dataRetirada DATETIME,
	dataDev DATETIME
);
